---
# Input files
CSVFile: './Example_CSV/Data_Example_val.csv'
ModelName: './pytorch_Model2_Tiles1x1_uniform_lr1e-3.h5'

# Output files
OutputFolder: 'DNN_Output/'
OutputSuffix: 'Pred_Model2_Tiles1x1_uniform'

# Data parameters
NbImageLayers: 122
TileSize: 15
AdjacentTilesDim: 1 # 1 for 1x1, 3 for 3x3, 5 for 5x5 adjacent tiles

# # Data sampling parameters
# num_workers: 6
# samples_per_volume: 1000
# queue_length: 6000 # samples_per_volume * num_workers

# Neural network parameters
# Model - FC layers
dict_fc_features:
  Phase1: [2048,512,256,64]
  Phase2: [128,64,32]
# Batch size
bs: 5000
